kind: Deployment
apiVersion: apps/v1
metadata:
   name: sampleapp
spec:
   replicas: 2
   selector:   
    matchLabels:
     app: sampleapp
   template:
      metadata:
        labels:
          app: sampleapp
      spec:
       containers:
        - name: node1
          image: erj56/pipe:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000