apiVersion: apps/v1
kind: Deployment
metadata:
   name: sampleapp
spec:
   replicas: 2
   selector:   
    matchLabels:
     app: sampleapp
   template:
      metadata:
        labels:
          app: sampleapp
      spec:
       containers:
        - name: con1
          image: "erj56/k8_web:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 80