apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
    - protocol:TCP
      port: 5000                               
      targetPort: 3000                    
      nodePort: 31110                 
  type: LoadBalancer                   
