apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
    - port: 80                               
      targetPort: 80                    
      nodePort: 30008                 
  type: NodePort                   
