kind: Service                             
apiVersion: v1
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: sampleapp                    
  type: LoadBalancer                   
